### ISSUE TITLE
Exception while invoking method

### ISSUE THREAD

**Issue by jeremyhodges** [DispatchMe/meteor-twilio#5]
For the life of me I can't get this to work. I get the following error when I try to use this from within a meteor method:

```
I20150526-19:13:22.623(-4)? Exception while invoking method 'sendSMS' [object Object]
I20150526-19:13:22.623(-4)?     at Object.Future.wait (/Users/jeremyhodges/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150526-19:13:22.623(-4)?     at RestClient.<anonymous> (packages/meteor/helpers.js:119:1)
I20150526-19:13:22.623(-4)?     at [object Object].Twilio.sendSMS (packages/dispatch:twilio/twilio.js:42:1)
I20150526-19:13:22.623(-4)?     at [object Object].Meteor.methods.sendSMS (app/server/index.js:225:18)
I20150526-19:13:22.624(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:160:1)
I20150526-19:13:22.624(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150526-19:13:22.624(-4)?     at packages/ddp/livedata_server.js:648:1
I20150526-19:13:22.624(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150526-19:13:22.624(-4)?     at packages/ddp/livedata_server.js:647:1
I20150526-19:13:22.624(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

I've added in the package to my project and have the following method:

``` javascript
  sendSMS: function() {
    var twilioClient = new Twilio({
      from: Meteor.settings.TWILIO.FROM,
      sid: Meteor.settings.TWILIO.SID,
      token: Meteor.settings.TWILIO.TOKEN
    });

    // Send a message
    twilioClient.sendSMS({
      to: '+19808758499',
      body: 'hello world'
    });

    return true;
  }
```

``` javascript
    Meteor.call('sendSMS');
```

**Comment by codeNgamer** [comment]
+1

**Comment by lionellei** [comment]
Exact same error for me!

**Comment by yoepus** [comment]
It is not mentioned in the readme, but to use this package you need to:
1. download the npm twilio package: npm install twilio
2. load npm into meteor, you can use meteorhack npm: meteor add meteorhacks:npm
3. this package and some finger crossing

good luck!
